routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {	
	/* member */
	Route::post('/member/print', 'MemberController@printCard');
	
	/* setting */
	Route::get('/setting', 'SettingController@form')->name('setting.form');
	Route::post('/setting', 'SettingController@save')->name('setting.save');
	
	/* purchase */
	Route::get('/purchase/show-supplier', 'ProductPurchaseController@showSupplier')->name('purchase.show-supplier');
	Route::get('/purchase/show-product', 'ProductPurchaseController@showProduct')->name('purchase.show-product');
	Route::post('/purchase/product/{code}', 'ProductPurchaseController@addToCart')->name('purchase.add-cart');
	Route::patch('/purchase/product/{code}', 'ProductPurchaseController@updateCart')->name('purchase.update-cart');
	Route::delete('/purchase/product/{code}', 'ProductPurchaseController@removeItemCart')->name('purchase.remove-item-cart');
	Route::post('/purchase/load-format', 'ProductPurchaseController@loadFormat')->name('purchase.load-format');

	/* sale */
	Route::get('sale', 'SaleController@index')->name('sale.index');
	Route::get('sale/bulk', 'SaleController@bulkBasePrice');
	Route::get('sale/{id}', 'SaleController@show')->name('sale.show');
	Route::get('sale/{id}/print', 'SaleController@print')->name('sale.print');
	Route::get('sale/{id}/edit', 'SaleController@edit')->name('sale.edit')->middleware('role:admin');
	Route::patch('sale/{id}', 'SaleController@update')->name('sale.update')->middleware('role:admin');
	Route::delete('sale/{id}', 'SaleController@destroy')->name('sale.destroy')->middleware('role:admin');

	/* product */
	Route::post('/product/delete-selected', 'ProductController@deleteSelected')->middleware('role:admin');
   	Route::post('/product/print-barcode', 'ProductController@printBarcode');
   	Route::post('/product/{id}/activate', 'ProductController@activate');
	Route::get('product', 'ProductController@index')->name('product.index');
	Route::post('product', 'ProductController@store')->name('product.store');
	Route::get('product/{id}', 'ProductController@show')->name('product.show');
	Route::get('product/{id}/edit', 'ProductController@edit')->name('product.edit')->middleware('role:admin');
	Route::patch('product/{id}', 'ProductController@update')->name('product.update')->middleware('role:admin');
	Route::delete('product/{id}', 'ProductController@destroy')->name('product.destroy')->middleware('role:admin');
	
	/* profile */
	Route::get('profile', 'UserController@showProfile')->name('profile.show');
	Route::post('profile', 'UserController@updateProfile')->name('profile.update');
	Route::get('profile/password', 'UserController@showPassword')->name('password.show');
	Route::post('profile/password', 'UserController@updatePassword')->name('password.update');

	Route::resource('category', 'CategoryController')->middleware('role:admin');
	Route::resource('member', 'MemberController')->middleware('role:admin');
	Route::resource('supplier', 'SupplierController')->middleware('role:admin');
	Route::resource('expenditure', 'ExpenditureController')->middleware('role:admin');
	Route::resource('user', 'UserController')->middleware('role:admin');

	Route::resource('purchase', 'ProductPurchaseController');
	
	// laporan
	Route::get('/report/income', 'ReportController@indexIncome')->name('report.income.index');
	Route::get('/report/income/pdf', 'ReportController@pdfIncome')->name('report.income.pdf');
	Route::get('/report/sales', 'ReportController@indexSales')->name('report.sales.index');
	Route::get('/report/sales/pdf', 'ReportController@pdfSales')->name('report.sales.pdf');

	Route::group(['middleware'=>['role:cashier']], function () {
		Route::get('/transaction', 'TransactionController@index')->name('transaction.index');
		Route::post('/transaction', 'TransactionController@store')->name('transaction.store');
		Route::get('/transaction/print/{sale_id}', 'TransactionController@printReceipt')->name('transaction.print');
		Route::get('/transaction/show-product', 'TransactionController@showProduct')->name('transaction.show-product');
		Route::get('/transaction/show-member', 'TransactionController@showMember')->name('transaction.show-member');
		Route::post('/transaction/product/{code}', 'TransactionController@addToCart')->name('transaction.add-cart');
		Route::patch('/transaction/product/{code}', 'TransactionController@updateCart')->name('transaction.update-cart');
		Route::delete('/transaction/product/{code}', 'TransactionController@removeItemCart')->name('transaction.remove-item-cart');
		Route::post('/transaction/load-format', 'TransactionController@loadFormat')->name('transaction.load-format');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $appends = ['role_human'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole($name)
    {
        if ($this->role === $name){
            return true;
        } 
         
        return false;
    }

    public function getRoleHumanAttribute()
    {
        if ($this->attributes['role'] != null) {
            if ($this->attributes['role'] == 'admin') {
                $role = 'Administrator';
            } elseif ($this->attributes['role'] == 'warehouse') {
                $role = 'Gudang';
            } elseif ($this->attributes['role'] == 'cashier') {
                $role = 'Kasir';
            }
        } else {
            return $this->attributes['role'];
        }

        return $role;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\File;
use App\User;
use App\ProductPurchase;
use App\Sale;
use Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $users = User::query();
            return Datatables::of($users)
                ->addIndexColumn()
                ->addColumn('avatars', function ($user) {
                    return view('partials._image', [
                        'model'           => $user,
                        'image_url'       => url('img', $user->avatar)
                    ]);
                })
                ->addColumn('action', function($user){
                    return view('partials._action', [
                        'model'           => $user,
                        'form_url'        => route('user.destroy', $user->id),
                        'edit_id'         => $user->id
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'name' => 'required|string',
            'email' => 'required|string|unique:users',
            'password' => 'required|min:6|confirmed',
            'role' => 'required|string',
        ]);

        if ($validator->passes()) {
            // Store to database  
            $user = new User;
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->avatar = $request->input('avatar', 'user-default.jpg');
            $user->role = $request->role;
            $user->save();

            return response()->json(['success' => '1']);
        }
        
        return response()->json(['errors' => $validator->errors()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return response()->json($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'name' => 'required|string',
            'email' => 'required|string|unique:users,email,' . $id,
            'password' => 'nullable|min:6|confirmed',
            'role' => 'required|string',
        ]);

        if ($validator->passes()) {
            // Store to database  
            $user = User::find($id);
            $user->name = $request->name;
            $user->email = $request->email;
            if ($request->input('password') != '') {
                $user->password = Hash::make($request->password);
            }
            $user->avatar = $request->input('avatar', 'user-default.jpg');
            $user->role = $request->role;
            $user->save();

            return response()->json(['success' => '1']);
        }
        
        return response()->json(['errors' => $validator->errors()]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        
        // cek self destroy
        if (\Auth::user()->id == $id) {
            Session::flash("flash_notification", [
                "level"=>"warning",
                "message"=>"Tidak dapat menghapus diri sendiri :p"
            ]);
            return redirect()->back();
        }

        if ($user->hasRole('warehouse') || $user->hasRole('admin')) {
            // cek pembelian
            $purchase = ProductPurchase::where('user_id',$id)->count();

            if ($purchase > 0) {
                Session::flash("flash_notification", [
                    "level"=>"warning",
                    "message"=>"Tidak dapat menghapus user yang sudah melakukan transaksi pembelian!"
                ]);
                return redirect()->back();
            }
        }

        if ($user->hasRole('cashier')) {
             // cek apakah user sudah melakukan penjualan
            $sale = Sale::where('user_id', $id)->count();
            
            if ($sale > 0) {
                Session::flash("flash_notification", [
                    "level"=>"warning",
                    "message"=>"Tidak dapat menghapus user yang sudah melakukan transaksi penjualan!"
                ]);
                return redirect()->back();
            }
        }
        
        $user->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('user.index');
    }

    public function showProfile()
    {
        $auth = \Auth::user()->id;
        $user = User::find($auth);
        return view('users.profile', ['user' => $user]);
    }

    public function updateProfile(Request $request)
  	{
  		$auth = \Auth::user()->id;
        $user = User::find($auth);
  		
  		$this->validate($request, [
  			'name' => 'required',
  			'email' => 'required|unique:users,email,' . $user->id,
  			'avatar' => 'image|max:1024',
  		]);

        if ($request->hasFile('avatar')) {
            // menambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('avatar');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            // memindahkan file ke folder public/img
            $uploaded_image->move($destinationPath, $filename);
            // hapus image lama, jika ada
            if ($user->avatar) {
                $old_image = $user->avatar;
                if ($user->avatar != 'user-default.jpg') {
                    # dete if not default
                    $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                    . DIRECTORY_SEPARATOR . $user->avatar;
                    try {
                        File::delete($filepath);
                    } catch (FileNotFoundException $e) {
                        // File sudah dihapus/tidak ada
                    }
                }
            }
            // ganti field image dengan image yang baru
            $user->avatar = $filename;
        }

        $user->name = $request->input('name');
        $user->email = $request->input('email');        
        $user->save();
  	
  		Session::flash("flash_notification", [
  			"level"=>"success",
  			"message"=>"Profil berhasil diubah"
  		]);

  		return redirect()->route('profile.show');
    }
      
    public function showPassword()
    {
        return view('users.password');
    }

    public function updatePassword(Request $request){
        $auth = \Auth::user()->id;
        $user = User::find($auth);

        $this->validate($request, [
            'password' => 'required|passcheck:' . $user->password,
            'new_password' => 'required|confirmed|min:6',
        ], [
            'password.passcheck' => 'Password lama tidak sesuai'
        ]);

        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Password berhasil diubah"
        ]);

        return redirect()->route('password.show');
    }
}

resources/views/users/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-lg">
     <div class="modal-content">
     
			<form class="form-horizontal" data-toggle="validator" method="post">
				{{ csrf_field() }} {{ method_field('POST') }}
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="clearError()"><span aria-hidden="true"> &times; </span> </button>
					<h3 class="modal-title"></h3>
				</div>
									
				<div class="modal-body">
					
					<input type="hidden" id="id" name="id">
					
					<div class="form-group">
						<label for="name" class="col-md-3 control-label">Nama Lengkap</label>
						<div class="col-md-6">
							<input id="name" type="text" class="form-control" name="name" autofocus>
							<span class="help-block with-errors"><strong id="name-error"></strong></span>
						</div>
					</div>

					<div class="form-group">
						<label for="email" class="col-md-3 control-label">Email</label>
						<div class="col-md-6">
							<input id="email" type="text" class="form-control" name="email">
							<span class="help-block with-errors"><strong id="email-error"></strong></span>
						</div>
					</div>

					<div class="form-group">
							<label for="password" class="col-md-3 control-label">Password</label>
							<div class="col-md-6">
								<input id="password" type="password" class="form-control" name="password">
								<span class="help-block with-errors"><strong id="password-error"></strong></span>
							</div>
					</div>

					<div class="form-group">
							<label for="password_confirmation" class="col-md-3 control-label">Konfirmasi Password</label>
							<div class="col-md-6">
								<input id="password_confirmation" type="password" class="form-control" data-match="#password" name="password_confirmation">
								<span class="help-block with-errors"></span>
							</div>
					</div>

					<div class="form-group">
						<label for="role" class="col-md-3 control-label">Hak Akses</label>
						<div class="col-md-6">
							<select name="role" id="role" class="form-control">
								<option value="admin">Administrator</option>
								<option value="warehouse">Gudang</option>
								<option value="cashier">Kasir</option>
							</select>
							<span class="help-block with-errors"><strong id="role-error"></strong></span>
						</div>
					</div>
					
				</div>
				
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
					<button type="button" class="btn btn-warning" data-dismiss="modal" onclick="clearError()"><i class="fa fa-arrow-circle-left"></i> Batal</button>
				</div>

			</form>

		</div>
	</div>
</div>

resources/views/users/index.blade.php
@extends('layouts.main')

@section('title')
  Daftar User
@endsection

@section('breadcrumb')
   @parent
   <li>User</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">  

			<table class="table table-striped datatable">
				<thead>
					<tr>
							<th width="30">No</th>
							<th>Nama User</th>
							<th>Email</th>
							<th>Avatar</th>
							<th>Hak Akses</th>
							<th width="100">Aksi</th>
					</tr>
				</thead>
				<tbody></tbody>
			</table>

      </div>
    </div>
  </div>
</div>

@include('users.form')
@endsection

@section('script')
<script type="text/javascript">
	var table, save_method;
	$(document).ready(function() {
		table = $('.datatable').DataTable({
			processing: true,
			serverSide: true,
			autoWidth: false,
			ajax: '{{ route('user.index') }}',
			columns: [
				{data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
				{data: 'name', name: 'name'},
				{data: 'email', name: 'email'},
				{data: 'avatars', name: 'avatar', orderable: false, searchable: false},
				{data: 'role_human', name: 'role'},
				{data: 'action', name: 'action', orderable: false, searchable: false},
			]
		});

		$('#modal-form form').on('submit', function(e){
			if(!e.isDefaultPrevented()){
				clearError();

				var id = $('#id').val();
				if(save_method == "add") 
					url = "{{ route('user.store') }}";
				else 
					url = "user/"+id;
				
				$.ajax({
					url : url,
					type : "POST",
					data : $('#modal-form form').serialize(),
					success : function(data){
						console.log(data);
						if(data.errors) {
							if(data.errors.name){
								$('#name-error').html(data.errors.name[0]);
							}
							if(data.errors.email){
								$('#email-error').html(data.errors.email[0]);
							}
							if(data.errors.password){
								$('#password-error').html(data.errors.password[0]);
							}
							if(data.errors.role){
								$('#role-error').html(data.errors.role[0]);
							}
						}
						if(data.success) {
							$('#modal-form').modal('hide');
							table.ajax.reload();
						}
					},
					error : function(){
						alert("Tidak dapat menyimpan data!");
					}   
				});
				return false;
			}
		});

		$(document).on('click','.js-submit-confirm', function(e){
			e.preventDefault();
			swal({
				title: 'Apakah anda yakin ingin menghapus?',
				text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
				icon: 'warning',
				buttons: true,
				dangerMode: true,
			})
			.then((willDelete) => {
				if (willDelete) {
					$(this).closest('form').submit();
				} 
			});
		});
	});

	function clearError() {
			$('#name-error').html("");
			$('#email-error').html("");
			$('#password-error').html("");
			$('#role-error').html("");
	}

	function addForm(){
		save_method = "add";
		$('input[name=_method]').val('POST');
		$('#modal-form').modal('show');
		$('#modal-form form')[0].reset();            
		$('.modal-title').text('Tambah User');
	}

	function editForm(id){
		save_method = "edit";
		$('input[name=_method]').val('PATCH');
		$('#modal-form form')[0].reset();
		$.ajax({
			url : "user/"+id+"/edit",
			type : "GET",
			dataType : "JSON",
			success : function(data){
				$('#modal-form').modal('show');
				$('.modal-title').text('Edit User');
				
				$('#id').val(data.id);
				$('#name').val(data.name);
				$('#email').val(data.email);
				$('#role').val(data.role);
				
			},
			error : function(){
				alert("Tidak dapat menampilkan data!");
			}
		});
	}
</script>
@endsection

resources/views/users/password.blade.php
@extends('layouts.main')

@section('title')
  Profile
@endsection

@section('breadcrumb')
   @parent
   <li>Profile</li>
   <li>Password</li>
@endsection

@section('content')     
<div class="row">
	<form class="form form-horizontal" data-toggle="validator" method="post" action="{{ route('password.update') }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="col-md-12">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Ubah Password</h3>
				</div>
				<div class="box-body">
          <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
              <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Password Lama</label>
              <div class="col-md-4 col-sm-6 col-xs-12">
                  <input type="password" class="form-control" name="password" value="{{ old('password') }}">
                  @if ($errors->has('password'))
                      <span class="help-block">
                          <strong>{{ $errors->first('password') }}</strong>
                      </span>
                  @endif
              </div>
          </div>
          <div class="form-group{{ $errors->has('new_password') ? ' has-error' : '' }}">
              <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Password Baru</label>
              <div class="col-md-4 col-sm-6 col-xs-12">
                  <input type="password" class="form-control" name="new_password" value="{{ old('new_password') }}">
                  @if ($errors->has('new_password'))
                      <span class="help-block">
                          <strong>{{ $errors->first('new_password') }}</strong>
                      </span>
                  @endif
              </div>
          </div>
          <div class="form-group">
            <label for="content" class="col-md-4 col-sm-4 col-xs-12 control-label">Konfirmasi Password Baru</label>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <input type="password" name="new_password_confirmation" class="form-control">
            </div>
          </div>
          <div class="form-group">
              <div class="col-md-4 col-sm-6 col-xs-12 col-md-offset-4">
                  <button type="submit" class="btn btn-primary">
                      <i class="fa fa-floppy-o"></i> Simpan
                  </button>
              </div>
          </div>
				</div>
			</div>
		
		</div>
	</form>
</div>

@endsection

resources/views/users/profile.blade.php
@extends('layouts.main')

@section('title')
  Profile
@endsection

@section('breadcrumb')
   @parent
   <li>Profile</li>
@endsection

@section('content')     
<div class="row">
	<form class="form form-horizontal" data-toggle="validator" method="post" action="{{ route('profile.update') }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="col-md-12">
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Ubah Profile</h3>
				</div>
				<div class="box-body">
					
					<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name" class="col-md-4 control-label">Nama</label>
						<div class="col-md-6">
							<input id="name" type="text" class="form-control" name="name" value="{{$user->name}}">
							@if ($errors->has('name'))
								<span class="help-block">
										<strong>{{ $errors->first('name') }}</strong>
								</span>
							@endif
						</div>
					</div>

					<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
						<label for="email" class="col-md-4 control-label">Email</label>
						<div class="col-md-6">
							<textarea name="email" rows="3" class="form-control">{{$user->email}}</textarea>
							@if ($errors->has('email'))
								<span class="help-block">
										<strong>{{ $errors->first('email') }}</strong>
								</span>
							@endif
						</div>
					</div>

					<div class="form-group{{ $errors->has('avatar') ? ' has-error' : '' }}">
						<label for="avatar" class="col-md-4 control-label">
							Avatar
						</label>
						<div class="col-md-6">
							<input id="avatar" type="file" class="form-control" name="avatar">
							<small class="pull-right"><i>*gunakan foto dengan rasio 1:1 / kotak | maximum size 1MB</i></small>
							@if ($errors->has('avatar'))
								<span class="help-block">
										<strong>{{ $errors->first('avatar') }}</strong>
								</span>
							@endif
							<br>
							<div class="tampil-logo">
								@if (!is_null($user->avatar))
									<img src="{{ asset('img/'.$user->avatar) }}" width="200" class="img-thumbnail">
								@endif
							</div>
						</div>
					</div>

					<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
						<label for="password" class="col-md-4 control-label">Password</label>
						<div class="col-md-6">
							<a href="{{route('password.show')}}" class="btn btn-default btn-sm"><i class="fa fa-lock"></i> Ubah Password</a>
							@if ($errors->has('password'))
								<span class="help-block">
										<strong>{{ $errors->first('password') }}</strong>
								</span>
							@endif
						</div>
					</div>

					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-floppy-o"></i> Simpan Perubahan</button>

				</div>
			</div>
		
		</div>
	</form>
</div>

@endsection