routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'main', 'middleware'=>['auth']], function () {	
	/* member */
	Route::post('/member/print', 'MemberController@printCard');
	
	/* setting */
	Route::get('/setting', 'SettingController@form')->name('setting.form');
	Route::post('/setting', 'SettingController@save')->name('setting.save');
	
	/* purchase */
	Route::get('/purchase/show-supplier', 'ProductPurchaseController@showSupplier')->name('purchase.show-supplier');
	Route::get('/purchase/show-product', 'ProductPurchaseController@showProduct')->name('purchase.show-product');
	Route::post('/purchase/product/{code}', 'ProductPurchaseController@addToCart')->name('purchase.add-cart');
	Route::patch('/purchase/product/{code}', 'ProductPurchaseController@updateCart')->name('purchase.update-cart');
	Route::delete('/purchase/product/{code}', 'ProductPurchaseController@removeItemCart')->name('purchase.remove-item-cart');
	Route::post('/purchase/load-format', 'ProductPurchaseController@loadFormat')->name('purchase.load-format');

	/* sale */
	Route::get('sale', 'SaleController@index')->name('sale.index');
	Route::get('sale/bulk', 'SaleController@bulkBasePrice');
	Route::get('sale/{id}', 'SaleController@show')->name('sale.show');
	Route::get('sale/{id}/print', 'SaleController@print')->name('sale.print');
	Route::get('sale/{id}/edit', 'SaleController@edit')->name('sale.edit')->middleware('role:admin');
	Route::patch('sale/{id}', 'SaleController@update')->name('sale.update')->middleware('role:admin');
	Route::delete('sale/{id}', 'SaleController@destroy')->name('sale.destroy')->middleware('role:admin');

	/* product */
	Route::post('/product/delete-selected', 'ProductController@deleteSelected')->middleware('role:admin');
   	Route::post('/product/print-barcode', 'ProductController@printBarcode');
   	Route::post('/product/{id}/activate', 'ProductController@activate');
	Route::get('product', 'ProductController@index')->name('product.index');
	Route::post('product', 'ProductController@store')->name('product.store');
	Route::get('product/{id}', 'ProductController@show')->name('product.show');
	Route::get('product/{id}/edit', 'ProductController@edit')->name('product.edit')->middleware('role:admin');
	Route::patch('product/{id}', 'ProductController@update')->name('product.update')->middleware('role:admin');
	Route::delete('product/{id}', 'ProductController@destroy')->name('product.destroy')->middleware('role:admin');
	
	/* profile */
	Route::get('profile', 'UserController@showProfile')->name('profile.show');
	Route::post('profile', 'UserController@updateProfile')->name('profile.update');
	Route::get('profile/password', 'UserController@showPassword')->name('password.show');
	Route::post('profile/password', 'UserController@updatePassword')->name('password.update');

	Route::resource('category', 'CategoryController')->middleware('role:admin');
	Route::resource('member', 'MemberController')->middleware('role:admin');
	Route::resource('supplier', 'SupplierController')->middleware('role:admin');
	Route::resource('expenditure', 'ExpenditureController')->middleware('role:admin');
	Route::resource('user', 'UserController')->middleware('role:admin');

	Route::resource('purchase', 'ProductPurchaseController');
	
	// laporan
	Route::get('/report/income', 'ReportController@indexIncome')->name('report.income.index');
	Route::get('/report/income/pdf', 'ReportController@pdfIncome')->name('report.income.pdf');
	Route::get('/report/sales', 'ReportController@indexSales')->name('report.sales.index');
	Route::get('/report/sales/pdf', 'ReportController@pdfSales')->name('report.sales.pdf');

	Route::group(['middleware'=>['role:cashier']], function () {
		Route::get('/transaction', 'TransactionController@index')->name('transaction.index');
		Route::post('/transaction', 'TransactionController@store')->name('transaction.store');
		Route::get('/transaction/print/{sale_id}', 'TransactionController@printReceipt')->name('transaction.print');
		Route::get('/transaction/show-product', 'TransactionController@showProduct')->name('transaction.show-product');
		Route::get('/transaction/show-member', 'TransactionController@showMember')->name('transaction.show-member');
		Route::post('/transaction/product/{code}', 'TransactionController@addToCart')->name('transaction.add-cart');
		Route::patch('/transaction/product/{code}', 'TransactionController@updateCart')->name('transaction.update-cart');
		Route::delete('/transaction/product/{code}', 'TransactionController@removeItemCart')->name('transaction.remove-item-cart');
		Route::post('/transaction/load-format', 'TransactionController@loadFormat')->name('transaction.load-format');
	});
});

app/Expenditure.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Expenditure extends Model
{
    //
}

app/Http/Controllers/ExpenditureController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Expenditure;
use Session;

class ExpenditureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $expenditures = Expenditure::query();
            return Datatables::of($expenditures)
                ->addIndexColumn()
                ->addColumn('date_format', function ($expenditure) {
                    return date('d-m-Y', strtotime($expenditure->date));
                })
                ->addColumn('nominal_f', function ($expenditure) {
                    return ('Rp '.rupiah_format($expenditure->nominal));
                })
                ->addColumn('action', function($expenditure){
                    return view('partials._action', [
                        'model'           => $expenditure,
                        'form_url'        => route('expenditure.destroy', $expenditure->id),
                        'edit_id'         => $expenditure->id
                    ]);
                })
                ->make(true);
        }

        return view('expenditures.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'date' => 'required|date',
            'type' => 'required|string',
            'nominal' => 'required',
        ]);

        if ($validator->passes()) {
            // Store to database  
            $expenditure = new Expenditure;
            $expenditure->date = $request->date;
            $expenditure->type = $request->type;
            $expenditure->nominal = str_replace(".", "", $request->nominal);
            $expenditure->save();

            return response()->json(['success' => '1']);
        }
        
        return response()->json(['errors' => $validator->errors()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $expenditure = Expenditure::findOrFail($id);
        return response()->json($expenditure);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'date' => 'required|date',
            'type' => 'required|string',
            'nominal' => 'required',
        ]);

        if ($validator->passes()) {
            // Store to database  
            $expenditure = Expenditure::find($id);
            $expenditure->date = $request->date;
            $expenditure->type = $request->type;
            $expenditure->nominal = str_replace(".", "", $request->nominal);
            $expenditure->save();

            return response()->json(['success' => '1']);
        }
        
        return response()->json(['errors' => $validator->errors()]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $expenditure = Expenditure::findOrFail($id);
        $expenditure->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('expenditure.index');
    }
}

resources/views/expenditures/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-lg">
     <div class="modal-content">
     
			<form class="form-horizontal" data-toggle="validator" method="post">
				{{ csrf_field() }} {{ method_field('POST') }}
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="clearError()"><span aria-hidden="true"> &times; </span> </button>
					<h3 class="modal-title"></h3>
				</div>
									
				<div class="modal-body">
					
					<input type="hidden" id="id" name="id">
					
					<div class="form-group">
						<label for="date" class="col-md-3 control-label">Tanggal</label>
						<div class="col-md-6">
							<input id="date" type="text" class="form-control" name="date" autofocus>
							<span class="help-block with-errors"><strong id="date-error"></strong></span>
						</div>
					</div>

					<div class="form-group">
						<label for="type" class="col-md-3 control-label">Jenis Pengeluaran</label>
						<div class="col-md-6">
							<input id="type" type="text" class="form-control" name="type">
							<span class="help-block with-errors"><strong id="type-error"></strong></span>
						</div>
					</div>

					<div class="form-group">
						<label for="nominal" class="col-md-3 control-label">Nominal</label>
						<div class="col-md-6">
							<div class="input-group">
								<span class="input-group-addon">Rp</span>
								<input id="nominal" type="text" class="form-control money" name="nominal" autofocus>
							</div>
							<span class="help-block with-errors"><strong id="nominal-error"></strong></span>
						</div>
					</div>
					
				</div>
				
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
					<button type="button" class="btn btn-warning" data-dismiss="modal" onclick="clearError()"><i class="fa fa-arrow-circle-left"></i> Batal</button>
				</div>

			</form>

		</div>
	</div>
</div>

resources/views/expenditures/index.blade.php
@extends('layouts.main')

@section('title')
  Daftar Pengeluaran
@endsection

@section('breadcrumb')
   @parent
   <li>Pengeluaran</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">  
				<table class="table table-striped datatable">
				<thead>
					<tr>
						<th width="30">No</th>
						<th>Tanggal</th>
						<th>Jenis Pengeluaran</th>
						<th>Nominal</th>
						<th width="100">Aksi</th>
					</tr>
				</thead>
				<tbody></tbody>
				</table>
      </div>
    </div>
  </div>
</div>

@include('expenditures.form')
@endsection

@section('script')
<script type="text/javascript">
	var table, save_method;
	$(document).ready(function() {
		table = $('.datatable').DataTable({
			processing: true,
			serverSide: true,
			autoWidth: false,
			ajax: '{{ route('expenditure.index') }}',
			columns: [
				{data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
				{data: 'date_format', name: 'date'},
				{data: 'type', name: 'type'},
				{data: 'nominal_f', name: 'nominal'},
				{data: 'action', name: 'action', orderable: false, searchable: false},
			]
		});

		$('#modal-form form').on('submit', function(e){
			if(!e.isDefaultPrevented()){
				clearError();

				var id = $('#id').val();
				if(save_method == "add") 
					url = "{{ route('expenditure.store') }}";
				else 
					url = "expenditure/"+id;
				
				$.ajax({
					url : url,
					type : "POST",
					data : $('#modal-form form').serialize(),
					success : function(data){
						console.log(data);
						if(data.errors) {
							if(data.errors.date){
								$('#date-error').html(data.errors.date[0]);
							}
							if(data.errors.type){
								$('#type-error').html(data.errors.type[0]);
							}
							if(data.errors.nominal){
								$('#nominal-error').html(data.errors.nominal[0]);
							}
						}
						if(data.success) {
							$('#modal-form').modal('hide');
							table.ajax.reload();
						}
					},
					error : function(){
						alert("Tidak dapat menyimpan data!");
					}   
				});
				return false;
			}
		});

		$('#date').datepicker({
			format: 'yyyy-mm-dd',
			autoclose: true
		});

		$('.money').mask('000.000.000', {reverse: true});

		$(document).on('click','.js-submit-confirm', function(e){
			e.preventDefault();
			swal({
				title: 'Apakah anda yakin ingin menghapus?',
				text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
				icon: 'warning',
				buttons: true,
				dangerMode: true,
			})
			.then((willDelete) => {
				if (willDelete) {
					$(this).closest('form').submit();
				} 
			});
		});
	});

	function clearError() {
		$('#date-error').html("");
		$('#type-error').html("");
		$('#nominal-error').html("");
	}

	function addForm(){
		save_method = "add";
		$('input[name=_method]').val('POST');
		$('#modal-form').modal('show');
		$('#modal-form form')[0].reset();            
		$('.modal-title').text('Tambah Pengeluaran');
	}

	function editForm(id){
		save_method = "edit";
		$('input[name=_method]').val('PATCH');
		$('#modal-form form')[0].reset();
		$.ajax({
			url : "expenditure/"+id+"/edit",
			type : "GET",
			dataType : "JSON",
			success : function(data){
				$('#modal-form').modal('show');
				$('.modal-title').text('Edit Pengeluaran');
				
				$('#id').val(data.id);
				$('#date').val(data.date);
				$('#type').val(data.type);
				$('#nominal').val(data.nominal);
				
			},
			error : function(){
				alert("Tidak dapat menampilkan data!");
			}
		});
	}
</script>
@endsection